### ISSUE TITLE
Wrong Number of arguments (given 3, expected 2)

### ISSUE THREAD

**Issue by mahmoudgamal0** [rack/rack-attack#609]
I am currently using Rails 6, Rack Attack 6.6.1, redis gem v5.0.5 and redis server v7

My configuration for rack attack in the initializer is:

```
Rack::Attack.throttle("IP", limit: 5, period: 2) do |request|
  request.ip
end

Rack::Attack.cache.store = ActiveSupport::Cache::RedisCacheStore.new(url: 'redis://localhost:6379/1') 
```

And I get the following error:
<img width="1053" alt="Screen Shot 2023-06-05 at 5 38 14 PM" src="https://github.com/rack/rack-attack/assets/32039610/cb74217f-d827-4710-ab63-d55de4f8a160">

What should I do?

**Comment by grzuy** [comment]
Hi,

I think the problem you're having is not related to rack-attack.

From what I see it's some incompatibility you're hitting between your rails and redis version.

I think the problem will go away if you at least upgrade to rails `6.0.4`.

**Comment by viktorianer** [comment]
I encountered a similar error with `rails (6.1.7.8)`, `redis (5.3.0)`, and `rack-attack (6.3.1)`:

```bash
Rails -- Exception: ArgumentError: wrong number of arguments (given 3, expected 1..2)
~/.asdf/installs/ruby/3.1.6/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/cache/strategy/local_cache.rb:116:in `increment'
~/.asdf/installs/ruby/3.1.6/lib/ruby/3.1.0/delegate.rb:87:in `method_missing'
~/.asdf/installs/ruby/3.1.6/lib/ruby/gems/3.1.0/gems/rack-attack-6.3.1/lib/rack/attack/store_proxy/redis_cache_store_proxy.rb:23:in `increment'
```

### Context:

Previously, we were using `redis-rails (5.0.2)` with `redis-store (1.10.0)` and had the following configuration:

```ruby
config.cache_store = :redis_store, "redis://...", { ... }
```

We recently migrated to `redis (5.3.0)` and switched our cache store configuration to:

```ruby
config.cache_store = :redis_cache_store, { redis: ..., ... }
```

This switch seems to have caused the error due to differences in the APIs between `redis-store` and the `redis` gem used by `:redis_cache_store`.

---

### Solution:

I resolved the issue by explicitly configuring `rack-attack` to use the native `Redis` client instead of the default proxy, which is not compatible with the new `redis` gem:

```ruby
Rack::Attack.cache.store = Redis.new(url: "redis://...")
```

---

### Request for Confirmation:

Could you confirm if this is the correct approach when using `:redis_cache_store` with `rack-attack`? It seems the default `redis_cache_store_proxy` is incompatible with the `redis` gem due to API mismatches (e.g., `increment` accepting different arguments). If so, perhaps documentation could be updated to reflect this workaround or to highlight the difference between `redis-store` and the native `redis` gem.
